
package com.demo.clien;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Evhc", targetNamespace = "http://www.cliffordthames.com/ebusiness/menus/", wsdlLocation = "https://uat.jlr-menupricing.com/jlrmp/evhc-service/Evhc?wsdl")
public class Evhc
    extends Service
{

    private final static URL EVHC_WSDL_LOCATION;
    private final static WebServiceException EVHC_EXCEPTION;
    private final static QName EVHC_QNAME = new QName("http://www.cliffordthames.com/ebusiness/menus/", "Evhc");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://uat.jlr-menupricing.com/jlrmp/evhc-service/Evhc?wsdl");
        } catch (MalformedURLException ex) {
        	 System.out.println("aaa=============");
            e = new WebServiceException(ex);
           
        }
        EVHC_WSDL_LOCATION = url;
        EVHC_EXCEPTION = e;
    }

    public Evhc() {
        super(__getWsdlLocation(), EVHC_QNAME);
    }

    public Evhc(WebServiceFeature... features) {
        super(__getWsdlLocation(), EVHC_QNAME, features);
    }

    public Evhc(URL wsdlLocation) {
        super(wsdlLocation, EVHC_QNAME);
    }

    public Evhc(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EVHC_QNAME, features);
    }

    public Evhc(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Evhc(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EvhcSoap
     */
    @WebEndpoint(name = "EvhcSoap")
    public EvhcSoap getEvhcSoap() {
        return super.getPort(new QName("http://www.cliffordthames.com/ebusiness/menus/", "EvhcSoap"), EvhcSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EvhcSoap
     */
    @WebEndpoint(name = "EvhcSoap")
    public EvhcSoap getEvhcSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cliffordthames.com/ebusiness/menus/", "EvhcSoap"), EvhcSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EVHC_EXCEPTION!= null) {
            throw EVHC_EXCEPTION;
        }
        return EVHC_WSDL_LOCATION;
    }

}
